services:
    app:
        build:
            context: docker
            dockerfile: Dockerfile
        container_name: content-hub-app
        volumes:
            - .:/var/www
            - ./node_modules:/var/www/node_modules
        depends_on:
            - db
        networks:
            - content-hub
        environment:
            DB_HOST: content-hub-db
            DB_PORT: 5432
            DB_USERNAME: user
            DB_PASSWORD: 123456
            DB_DATABASE: content_hub

    db:
        image: postgres:15
        container_name: content-hub-db
        environment:
            POSTGRES_DB: content_hub
            POSTGRES_USER: user
            POSTGRES_PASSWORD: 123456
        ports:
            - "5433:5432"
        volumes:
            - content-hub:/var/lib/postgresql/data
        networks:
            - content-hub

    nginx:
        image: nginx:alpine
        container_name: content-hub-nginx
        ports:
            - "90:80"
        volumes:
            - .:/var/www
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - content-hub

volumes:
    content-hub:

networks:
    content-hub:

