FROM php:8.4-fpm
WORKDIR /var/www/shuhrat

RUN apt-get update && apt-get install -y \
    libpng-dev \
    libjpeg-dev \
    libonig-dev \
    libxml2-dev \
    libzip-dev \
    unzip \
    curl \
    && docker-php-ext-install pdo pdo_pgsql pgsql mbstring exif pcntl bcmath gd zip

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

#RUN chown -R www-data:www-data /var/www/shuhrat \
#    && chmod -R 755 /var/www/shuhrat/storage /var/www/shuhrat/bootstrap/cache

CMD ["php-fpm"]


