name: Deploy Laravel App

on:
  push:
    branches:
      - SShuhratt-patch-1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          echo "${{ secrets.DEPLOY_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Add server to known_hosts
        run: ssh-keyscan 185.191.141.44 >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          ssh -i key.pem root@185.191.141.44 << 'EOF'
            cd /var/www/shuhrat/useful-contents-library
            git pull origin SShuhratt-patch-1
            composer install --no-interaction --prefer-dist --optimize-autoloader
            docker exec content-hub-app php artisan migrate --force
            docker exec content-hub-app php artisan config:cache
            docker exec content-hub-app php artisan route:cache
            docker exec content-hub-app php artisan view:cache
          EOF

      - name: Clean up SSH key
        run: rm -f key.pem
